### ISSUE TITLE
Unit test Telemetry SDK: video path 

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-vision-android#106]
Issue: wrong path name (missing or extra _language_, _location_)

**Comment by yunikkk** [comment]
Wont be relevant with #1739, logic building directory paths had moved to c++ code

**Comment by RingerJK** [comment]
I think that country/language/platform("Android") and etc will be provided by platform, does not?

**Comment by yunikkk** [comment]
> I think that country/language/platform("Android") and etc will be provided by platform, does not?

Yes, but core will combine them to prepare video path itself, we don't have such concept on platform. What we have is implementation of interfaces, and they can/should be covered with unit tests eventually. Though this task is about video path specifically

**Comment by RingerJK** [comment]
I believe, that problem here was Android platform provided wrong path name that was created on own side(based on `Context` -> `Resources` data). So unit tests on Core side won't solve this issues.

**Comment by yunikkk** [comment]
Lets discuss personally, not sure I understood you correctly

**Comment by kiryldz** [comment]
@yunikkk @RingerJK - did you discuss it personally? Could we close this?

**Comment by yunikkk** [comment]
Not really sure, long time no see with this issue=)

**Comment by kiryldz** [comment]
As discussed, Telemetry now moved to core completely. We could close this.
