### ISSUE TITLE
API to notify unsupported hardware configuration

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-vision-android#11]
This is an enhancement request. Currently, when trying to load the SDK into a device that isn't supported, the app would crash with the following message:

> kotlin.NotImplementedError: An operation is not implemented: Device does not support SNPE! Vision SDK does not work with this device yet.

Though this is expected and documented, we'd probably want to add a more graceful way to handle these situations. One possibility is providing an API method to detect if the device is supported, or an error callback so that developer can implement a recovery path.

**Comment by yunikkk** [comment]
API that checks if board is supported is
`SupportedSnapdragonBoards.isBoardSupported(SystemInfoUtils.getSnpeSupportedBoard())`.

We still need to update documentation to show this API usage.

**Comment by yunikkk** [comment]
Will close this ticket, seems its out of date. 
To check if device is supported we have the following API now : `SystemInfoUtils.isVisionSupported`
