### ISSUE TITLE
Add Snapdragon 855 variants to supported devices

### ISSUE THREAD

**Issue by BULVRDapp** [mapbox/mapbox-vision-android#118]
Snapdragon 855 was recently added to the list of supported devices

```
package com.mapbox.vision.mobile.core.utils.snapdragon

public final enum class SupportedSnapdragonBoards private constructor() : kotlin.Enum<com.mapbox.vision.mobile.core.utils.snapdragon.SupportedSnapdragonBoards> {
    SDM855,

    SDM845,

    MSM8998,

    MSM8996,

    SDM710,

    SDM660,

    MSM8956,

    MSM8952;

    public companion object {
        @kotlin.jvm.JvmStatic public final fun isBoardSupported(boardName: kotlin.String): kotlin.Boolean { /* compiled code */ }
    }
}
```

Some devices ship with prior used codenames of the Snapdragon 855, in our case we see references to _SM8150_ and board name _msmnile_

Are we able to get this added or have some way of enabling testing of different variants without these processor checks kicking in within the SDK?

**Comment by yunikkk** [comment]
@BULVRDapp we are still working on supporting 855 processor, it won't be supported right now. 
But we definitely can add some switch to turn off checks for debugging. We'll discuss internally this and get back to you.

**Comment by BULVRDapp** [comment]
Yeah we knew it wasn't originally supported due to a bug on the Qualcomm side, but we saw commits for it being add in [https://github.com/mapbox/mapbox-vision-android/commit/013a70b26d082b9dbd98d2de392d21a5eb9e0bd0](url) so assumed that had been cleared up.

Figured we'd pass along other 855 variants we see incase they were not known.

**Comment by yunikkk** [comment]
The bug is still there, so despite of model added to the list of supported processor won't run the models =\ 
We are tracking the issue and working on supporting 855, will get back as soon as it's ready

**Comment by BULVRDapp** [comment]
Seen the latest changelog update https://github.com/mapbox/mapbox-vision-android/commit/e5669e50d3fd2987430d7143d4c99a83acdff61d for adding 855 support. Is this build available now or is there a way we could help test this version out?

**Comment by yunikkk** [comment]
It's not released yet but we are very close, expect to arrive early next week. I'll post here as soon as it's there

**Comment by vladzima** [comment]
Latest 0.10.0 release https://vision.mapbox.com/install/ supports 855. Docs are coming up in a couple of days.
