### ISSUE TITLE
Unable to resolve dependency error

### ISSUE THREAD

**Issue by shahram95** [mapbox/mapbox-vision-android#120]
Hi, i am getting the following error when I am trying to sync the gradle:

ERROR: Unable to resolve dependency for ':Examples@debug/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debug/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debug/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-safety:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debug/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-safety-native:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-safety:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-safety-native:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debugUnitTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debugUnitTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debugUnitTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-safety:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@debugUnitTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-safety-native:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@release/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@release/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@release/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-safety:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@release/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-safety-native:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@releaseUnitTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@releaseUnitTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@releaseUnitTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-safety:0.4.0.
Show Details
Affected Modules: Examples

ERROR: Unable to resolve dependency for ':Examples@releaseUnitTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-safety-native:0.4.0.
Show Details
Affected Modules: Examples
`

The build.gradle(project) is:

`buildscript {
    if (file("${rootDir}/gradle/versions.gradle").exists()) {
        apply from: "${rootDir}/gradle/versions.gradle"
    }
    
    ext {
        dokka_version = '0.9.17'
        android_maven_plugin_version = '2.0'
        gradle_bintray_plugin = '1.8.0'
    }

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$gradle_plugin"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.dokka:dokka-android-gradle-plugin:$dokka_version"
        classpath "com.github.dcendents:android-maven-gradle-plugin:$android_maven_plugin_version"
        classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:$gradle_bintray_plugin"
        classpath "de.mannodermaus.gradle.plugins:android-junit5:$mannodermaus_junit5_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()

        maven { url "https://mapbox.bintray.com/mapbox" }

        maven {
            credentials {
                username 'shahram95'
                password 'sk.eyJ1Ijoic2hhaHJhbTk1IiwiYSI6ImNqeG81YmFhaTAzM2czbXA5emhlNWZ3dXgifQ.jrgjr8IHU02x6i5Us_CARQ'
            }
            authentication {
                basic(BasicAuthentication)
            }

            url 'https://api.mapbox.com/downloads/v1/vision/android/maven'
        }
    }
}
`

and the build.gradle (module) is:

`apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

apply from: 'generate-token.gradle'

apply from: "../gradle/ktlint.gradle"

def envVarOrLocalProperty(String name) {
    if (System.getenv(name) != null) {
        return System.getenv(name)
    }

    Properties properties = new Properties()
    def file = project.rootProject.file('local.properties')
    if (file.exists()) {
        properties.load(file.newDataInputStream())
        def localProperty = properties.getProperty(name)
        if (localProperty != null) {
            return localProperty
        }
    }
    return null
}

if (file("${rootDir}/gradle/versions.gradle").exists()) {
    apply from: "${rootDir}/gradle/versions.gradle"
}

android {
    compileSdkVersion 28

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    defaultConfig {
        applicationId "com.mapbox.vision.examples"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets {
        main {
            java.srcDirs += 'src/main/java'
            java.srcDirs += 'src/main/kotlin'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "androidx.appcompat:appcompat:$android_x_appcompat"
    implementation "androidx.constraintlayout:constraintlayout:$android_x_constraint_layout"

    implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:$mapbox_sdk"
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation:$mapbox_navigation"
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation-ui:$mapbox_navigation"
    implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:$mapbox_location_layer"
    implementation "com.mapbox.mapboxsdk:mapbox-android-core:$mapbox_core"

    implementation "com.mapbox.vision:mapbox-android-vision:0.4.0"
    implementation "com.mapbox.vision:mapbox-android-vision-ar:0.4.0"
    implementation "com.mapbox.vision:mapbox-android-vision-safety:0.4.0"

    ktlint "com.pinterest:ktlint:$ktlint_version"

    if (envVarOrLocalProperty('BUILD_CORE_FROM_SOURCE')?.toBoolean()) {
        implementation project(path: ':Vision')
        implementation project(path: ':VisionAr')
        implementation project(path: ':VisionSafety')
        implementation project(path: ':CoreAr')
        implementation project(path: ':CoreSdk')
        implementation project(path: ':CoreSafety')
    } else {
        implementation "com.mapbox.vision:mapbox-android-vision:$vision"
        implementation "com.mapbox.vision:mapbox-android-vision-ar:$vision_ar"
        implementation "com.mapbox.vision:mapbox-android-vision-safety:$vision_safety"
        implementation "com.mapbox.vision:mapbox-android-vision-safety-native:$vision_safety"
    }

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}`

could you guys help me out? kindly let me know if anything else is required. Thanks.

**Comment by RingerJK** [comment]
@shahram95 please replace  **_username 'shahram95'_** -> **_username 'mapbox'_**
