### ISSUE TITLE
Failing to resolve error

### ISSUE THREAD

**Issue by ai2015-try** [mapbox/mapbox-vision-android#125]
![error](https://user-images.githubusercontent.com/52096856/60769108-87ae5f80-a0fe-11e9-820d-061e7f6b230d.JPG)

So I'm following the tutorial on MapBox's website on how to implement Vision into the project and I'm running into this issue, I followed all the steps exactly. I have no idea why this is hapening

**Comment by yunikkk** [comment]
Hello, did you add mapbox maven repo to your top level build.gradle? Eg. 

```
maven {
  url 'https://api.mapbox.com/downloads/v1/vision/android/maven'
  authentication {
    basic(BasicAuthentication)
  }
  credentials {
    username = 'mapbox'
    password = 'ADD-YOUR-TOKEN'
  }
}
```
as shown in https://vision.mapbox.com/install/

**Comment by shahram95** [comment]
@ai2015-try , Hello, hope you are having a good day. I was facing the same problem, go to build.gradle(Project: mapbox-vision-android-dev) and add this maven repo as @yunikkk  mentioned.

> allprojects {
    repositories {
        google()
        jcenter()

        maven { url "https://mapbox.bintray.com/mapbox" }

        maven {
            url 'https://api.mapbox.com/downloads/v1/vision/android/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = 'mapbox'
                password = 'sk.eyJ1Ijoic2hhaHJhbTk1IiwiYSI6ImNqeG81YmFhaTAzM2czbXA5emhlNWZ3dXgifQ.jrgjr8IHU02x6i5Us_CARQ'
            }
        }
    }
}

**Comment by ai2015-try** [comment]
Thank you, the issue is fixed now :)
