### ISSUE TITLE
Update android Examples

### ISSUE THREAD

**Issue by korshaknn** [mapbox/mapbox-vision-android#132]
Examples don't work as needed, should be fixed.

**Comment by vladzima** [comment]
If the task is in Sprint, it should either be in Spring Backlog or In Progress (/PR) or Closed.

**Comment by vladzima** [comment]
Estimation?

**Comment by prat96** [comment]
Hi guys, I request for the examples to be cleaned up/implemented a lot better, half the stuff doesn't work without modification and it's not at all clear what exactly each example is supposed to do without really diving into the code. 
You could save new developers a lot of time and effort. Thanks!
