### ISSUE TITLE
Add Nokia 6.1 2018 with Snapdragon 630 to supported devices

### ISSUE THREAD

**Issue by thomhubers** [mapbox/mapbox-vision-android#142]
I ran the teaser app on this phone, refresh rate was like 1 fps (what is normal?) but it works.

**Comment by yunikkk** [comment]
Hey, thanks for trying, glad to hear it works!
Refresh rate depends solely on the hardware, GPU most importantly. Currently we state 650 Snap the lowest supported due to the low FPS on lower models. We'll consider adding more descriptive list of models that are supported.

**Comment by thomhubers** [comment]
Totally fine, just wanted to report my findings.

0.5.0 was a big improvement in speed, maybe in the future it will improve even further. If there's anything you'd like me to test on the cheaper supported hardware, just let me know.

**Comment by thomhubers** [comment]
https://versus.com/en/qualcomm-snapdragon-630-vs-qualcomm-snapdragon-650 this shows that 630 is supposed to be faster than 650. Am I overlooking something?

**Comment by yunikkk** [comment]
For Vision the main bottleneck will be GPU, which is Adreno 508 VS 510, https://www.notebookcheck.net/Adreno-508-vs-Adreno-510_8112_7360.247598.0.html. Mostly they are very similar, so the performance should be close, too.
