### ISSUE TITLE
Resolve circular dependency

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-vision-android#145]
`DelegateVisionManager` has dependency on `VisionView` while `VisionView` has dependency on `DelegateVisionManager` too, this is a circular dependency. In fact only `VisionView` should has dependency on `DelegateVisionManager`.

Solution:
Remove `externalVideoSourceListener` from `DelegateVisionManager` and set `baseVisionManager` of `VisionView` in `VisionManager`.

@yunikkk What do you think?

**Comment by yunikkk** [comment]
@Chaoba yup, that was quick and dirty solution, will fix it soon. Have a branch with the changes that will remove dependency DelegateVisionManager from VisionView
