### ISSUE TITLE
Read sensorsListener

### ISSUE THREAD

**Issue by thomhubers** [mapbox/mapbox-vision-android#150]
`VisionManager.start(visionEventsListener)` provides the method to listen for vision events. I discovered a sensorDataListener to be in the mapbox-vision sdk too. 

Is there a possibility to override the sensor listeners? Both the heading and deviceMotion are interesting.

**Comment by yunikkk** [comment]
@thomhubers could you please elaborate the use case for overrinding sensors?

**Comment by thomhubers** [comment]
I sent you an email.
