### ISSUE TITLE
Vision Example Code crash at `couldn't find "libvision-sdk-wrapper.so"`

### ISSUE THREAD

**Issue by code-player** [mapbox/mapbox-vision-android#200]
Following is the logcat 

> 09-04 15:29:46.806 2552-2552/com.mapbox.vision.examples E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.mapbox.vision.examples, PID: 2552
>     java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mapbox.vision.examples-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.vision.examples-2/lib/arm, /data/app/com.mapbox.vision.examples-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libvision-sdk-wrapper.so"
>         at java.lang.Runtime.loadLibrary(Runtime.java:367)
>         at java.lang.System.loadLibrary(System.java:1076)
>         at com.mapbox.vision.mobile.core.NativeVisionManager.<clinit>(NativeVisionManager.kt:37)
>         at com.mapbox.vision.VisionManager.create(VisionManager.kt:168)
>         at com.mapbox.vision.VisionManager.create$default(VisionManager.kt:165)
>         at com.mapbox.vision.VisionManager.create(VisionManager.kt)
>         at com.mapbox.vision.examples.ArActivity.onResume(ArActivity.java:120)
>         at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
>         at android.app.Activity.performResume(Activity.java:6361)
>         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
>         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
>         at android.app.ActivityThread.access$900(ActivityThread.java:150)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.app.ActivityThread.main(ActivityThread.java:5417)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>

**Comment by korshaknn** [comment]
@code-player hi! It can happen because of invalid linking during installation. Do you have enough free memory on the phone? Have you tried to reinstall the app?

**Comment by korshaknn** [comment]
@code-player please also note that we are fixing Examples right now, a PR with fixies is [here](https://github.com/mapbox/mapbox-vision-android/pull/199)

**Comment by yunikkk** [comment]
@code-player I see only `armeabi-v7a` referenced in the crashlog, which is not supported yet, only armv8 is. Which device are you running at?

**Comment by korshaknn** [comment]
@code-player current version of `ArActivity.java` doesn't have a `isSupportedDevice` check, it is fixed in the PR mentioned above

**Comment by code-player** [comment]
@yunikkk I was trying on lenovo tablet which is arm-v7 architecture.

@korshaknn I tried the PR you mentioned, following is the error log I get now in logcat.
> 2019-09-04 14:44:30.583 6809-6891/com.mapbox.vision.examples E/linker: library "/vendor/lib64/libOpenCL.so" ("/system/vendor/lib64/libOpenCL.so") needed or dlopened by "/data/app/com.mapbox.vision.examples-TZ4Eps9QBcwTVYCIwaCpCg==/lib/arm64/libSNPE.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.mapbox.vision.examples-TZ4Eps9QBcwTVYCIwaCpCg==/lib/arm64:/data/app/com.mapbox.vision.examples-TZ4Eps9QBcwTVYCIwaCpCg==/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.mapbox.vision.examples"]

Now, I'm trying with device that is `aarch64`.

**Comment by code-player** [comment]
@korshaknn I couldn't find the method `isSupportedDevice` as mentioned by you above.
Please confirm

**Comment by code-player** [comment]
@korshaknn Please confirm if the issue I reported above is fatal or can be ignored?

Moreover, after the `error log`, I can't see any kind of icon/ feature in the example app. All I get is my camera feed and a direction pop up in the notification bar of my phone, the distance of which does not change even when I move in the direction.

Am I missing something here? Please suggest.

**Comment by korshaknn** [comment]
@code-player Examples don't have a full functionality, they just like a code snippets to show you how the SDK can be used. If you need more complete example, please go to [Teaser app](https://github.com/mapbox/mapbox-vision-android-teaser)

**Comment by code-player** [comment]
I'm still facing issues with build. Moving to the Teaser app repo.

**Comment by rgouzal** [comment]
still facing issue, this issue should not be closed.

**Comment by yunikkk** [comment]
@rgouzal please submit fresh issue with the description of what you build and what's not working

**Comment by rgouzal** [comment]
> @rgouzal please submit fresh issue with the description of what you build and what's not working

I am trying to run the exact example but in emulator device.

**Comment by rgouzal** [comment]
> @rgouzal please submit fresh issue with the description of what you build and what's not working

@yunikkk I am trying to run the example from ArActivity.java in mapbox docs page but in emulator device.

**Comment by yunikkk** [comment]
> > @rgouzal please submit fresh issue with the description of what you build and what's not working
> 
> @yunikkk I am trying to run the example from ArActivity.java in mapbox docs page but in emulator device.

Ah, then it's clear - Vision won't run on the emulator anyway. You need device that is supported, more info here https://docs.mapbox.com/android/vision/guides/#requirements
