### ISSUE TITLE
Samsung S9 Not Supported

### ISSUE THREAD

**Issue by francorobles** [mapbox/mapbox-vision-android#203]
It say's Samsung S9 is not supported?

**Comment by francorobles** [comment]
I didn't noticed my processor was Exynos. Any plans of supporting this processor?

**Comment by korshaknn** [comment]
@francorobles currently we don't support Exynos processors, only Snapdragon. It would be great to support Exynos, but we are not working on it right now.

**Comment by yunikkk** [comment]
@francorobles hello, if you're still have interest you can try Vision with Exynos now using new 0.12.0 Vision SDK release.

**Comment by francorobles** [comment]
Thank your for the update.
