### ISSUE TITLE
How to pass user's location to the origin point? 

### ISSUE THREAD

**Issue by estherooi** [mapbox/mapbox-vision-android#223]
` How to pass the current user location to the origin point? Is there a method to put it? I tried many ways, but it seems like not working well? 
//Main activity
public class MainActivity extends AppCompatActivity {

    //location part
    FusedLocationProviderClient mFusedLocationClient;
    LocationRequest mLocationRequest;
    LocationCallback mLocationCallback;

    double pLat;
    double pLong;

    LocationSettingsRequest.Builder mLocationSettingsBuilder;
    SettingsClient client;
    Task<LocationSettingsResponse> task;
    private static final int REQUEST_CHECK_SETTINGS = 0X1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mFusedLocationClient = LocationServices.getFusedLocationProviderClient(MainActivity.this);
        mLocationCallback = new LocationCallback() {
            @Override
            public void onLocationResult(LocationResult locationResult) {
                if (locationResult == null) {

                    return;
                } else
//                            tvlocation.append("\n"+"Latitude: " + locationResult.getLastLocation().getLatitude() + "Longitude: " + locationResult.getLastLocation().getLongitude());

                    pLat = locationResult.getLastLocation().getLatitude();
                    pLong = locationResult.getLastLocation().getLongitude();

                Intent i = new Intent(MainActivity.this, ArActivity.class);

//                LatLng position = new LatLng(pLat, pLong);
//                Bundle args = new Bundle();
//                args.putParcelable("coordinate", position);
//                i.putExtras(args);

                i.putExtra("Latitude", pLat);
                i.putExtra("Longitude", pLong);

                startActivity(i);
            }

        };

        setLocationRequestSettings();

    }

    @Override
    protected void onResume() {
        super.onResume();
        //   startLocationUpdate();
        requestLocationUpdate();
    }

    @Override
    protected void onPause() {
        super.onPause();

        if(mFusedLocationClient!=null)
        {
            mFusedLocationClient.removeLocationUpdates(mLocationCallback);
            //   Toast.makeText(MainActivity.this, "Listener is Removed",Toast.LENGTH_SHORT).show();
        }
    }

    private void requestLocationUpdate()
    {
        mLocationSettingsBuilder = new LocationSettingsRequest.Builder().addLocationRequest(mLocationRequest);
        client = LocationServices.getSettingsClient(MainActivity.this);

        task = client.checkLocationSettings(mLocationSettingsBuilder.build());

        task.addOnSuccessListener(MainActivity.this, new OnSuccessListener<LocationSettingsResponse>() {
            @Override
            public void onSuccess(LocationSettingsResponse locationSettingsResponse) {
                startLocationUpdate();
            }
        });
        task.addOnFailureListener(MainActivity.this, new OnFailureListener() {
            @Override
            public void onFailure(@NonNull Exception e) {
                if(e instanceof ResolvableApiException)
                {
                    try
                    {
                        ResolvableApiException resolvable = (ResolvableApiException)e;
                        resolvable.startResolutionForResult(MainActivity.this, REQUEST_CHECK_SETTINGS);
                    } catch(IntentSender.SendIntentException sendEx)
                    {

                    }
                }
            }
        });
    }

    private void setLocationRequestSettings()
    {
        mLocationRequest = LocationRequest.create();
        //        mLocationRequest.setInterval(3000);
        //        mLocationRequest.setFastestInterval(1000);
        mLocationRequest.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);

    }

    private void startLocationUpdate()
    {
        // Here, thisActivity is the current activity
        if (ContextCompat.checkSelfPermission(MainActivity.this,
                Manifest.permission.ACCESS_FINE_LOCATION)
                != PackageManager.PERMISSION_GRANTED) {

            // Permission is not granted
            // Should we show an explanation?
            if (ActivityCompat.shouldShowRequestPermissionRationale(MainActivity.this,
                    Manifest.permission.ACCESS_FINE_LOCATION)) {
                // Show an explanation to the user *asynchronously* -- don't block
                // this thread waiting for the user's response! After the user
                // sees the explanation, try again to request the permission.
                showExplaination();

            } else {
                // No explanation needed; request the permission
                ActivityCompat.requestPermissions(MainActivity.this,
                        new String[]{Manifest.permission.ACCESS_FINE_LOCATION},
                        0);

                // MY_PERMISSIONS_REQUEST_READ_CONTACTS is an
                // app-defined int constant. The callback method gets the
                // result of the request.
            }
        } else {
            // Permission has already been granted
            mFusedLocationClient.requestLocationUpdates(mLocationRequest,mLocationCallback,null);
            //   Toast.makeText(MainActivity.this,"Location Permission was granted.",Toast.LENGTH_SHORT).show();
        }
    }
    private void showExplaination()
    {
        AlertDialog.Builder builder = new AlertDialog.Builder(MainActivity.this);

        builder.setTitle("Reqiores Location Permission");
        builder.setMessage("This app needs location permission to get the location information");
        builder.setPositiveButton("OK", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                ActivityCompat.requestPermissions(MainActivity.this,
                        new String[]{Manifest.permission.ACCESS_FINE_LOCATION},
                        0);
            }
        });

        builder.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                //     Toast.makeText(MainActivity.this, "Sorry, this function cannot be worked until the permission is granted", Toast.LENGTH_SHORT).show();
            }
        });
        builder.show();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case REQUEST_CHECK_SETTINGS:
                switch (resultCode) {
                    case Activity.RESULT_OK:
                        Toast.makeText(MainActivity.this, "Location setting has turned on", Toast.LENGTH_LONG).show();
                        break;

                    case Activity.RESULT_CANCELED:
                        Toast.makeText(MainActivity.this, "Location setting has not turned on", Toast.LENGTH_LONG).show();
                        break;
                }
        }
    }
}

`

`
//AR activity.java
/**
 * Example shows how Vision and VisionAR SDKs are used to draw AR lane over the video stream from camera.
 * Also, Mapbox navigation services are used to build route and  navigation session.
 */
public class ArActivity extends BaseActivity implements RouteListener, ProgressChangeListener, OffRouteListener {

    private static final String TAG = ArActivity.class.getSimpleName();

    // Handles navigation.
    private MapboxNavigation mapboxNavigation;
    // Fetches route from points.
    private RouteFetcher routeFetcher;
    private RouteProgress lastRouteProgress;
    private LocationEngine locationEngine;
    private LocationEngineCallback<LocationEngineResult> locationCallback;

    private boolean visionManagerWasInit = false;
    private boolean navigationWasStarted = false;

    double rLong;
    double rLat;

    Double[] array = new Double[2];

    public void getData(){
     Intent i =getIntent();
     rLat = i.getDoubleExtra("Latitude",0);
     rLong = i.getDoubleExtra("Longitude", 0);

    }

    public double getLongitude(){
       getData();
        return rLong;
    }

    public double getLatitude(){
        getData();
        return rLat;
    }

    // This dummy points will be used to build route. For real world test this needs to be changed to real values for
    // source and target locations.
    private final Point ROUTE_ORIGIN = Point.fromLngLat(getLongitude(),  getLatitude());
    private final Point ROUTE_DESTINATION = Point.fromLngLat(101.774753, 2.919751);

    @Override
    protected void initViews() {
        setContentView(R.layout.activity_ar_navigation);

    }

    @Override
    protected void onPermissionsGranted() {
        startVisionManager();
        startNavigation();

    }

    @Override
    protected void onStart() {
        super.onStart();
        startVisionManager();
        startNavigation();

    }

    @Override
    protected void onStop() {
        super.onStop();
        stopVisionManager();
        stopNavigation();
    }

    private void startVisionManager() {
        if (allPermissionsGranted() && !visionManagerWasInit) {
            // Create and start VisionManager.

            VisionManager.create();
            VisionManager.setModelPerformanceConfig(new Merged(new On(ModelPerformanceMode.DYNAMIC, ModelPerformanceRate.LOW)));
            VisionManager.start();
            VisionManager.setVisionEventsListener(new VisionEventsListener() {
                @Override
                public void onAuthorizationStatusUpdated(@NotNull AuthorizationStatus authorizationStatus) {
                }

                @Override
                public void onFrameSegmentationUpdated(@NotNull FrameSegmentation frameSegmentation) {
                }

                @Override
                public void onFrameDetectionsUpdated(@NotNull FrameDetections frameDetections) {
                }

                @Override
                public void onFrameSignClassificationsUpdated(@NotNull FrameSignClassifications frameSignClassifications) {
                }

                @Override
                public void onRoadDescriptionUpdated(@NotNull RoadDescription roadDescription) {
                }

                @Override
                public void onWorldDescriptionUpdated(@NotNull WorldDescription worldDescription) {
                }

                @Override
                public void onVehicleStateUpdated(@NotNull VehicleState vehicleState) {
                }

                @Override
                public void onCameraUpdated(@NotNull Camera camera) {
                }

                @Override
                public void onCountryUpdated(@NotNull Country country) {
                }

                @Override
                public void onUpdateCompleted() {
                }
            });

            VisionArView visionArView = findViewById(R.id.mapbox_ar_view);

            // Create VisionArManager.
            VisionArManager.create(VisionManager.INSTANCE);
            visionArView.setArManager(VisionArManager.INSTANCE);
            visionArView.setFenceVisible(true);

            visionManagerWasInit = true;
        }
    }
`

**Comment by kiryldz** [comment]
Hi @estherooi !
Firstly, could you please specify if this issue is copy of #222. If yes - please close #222.
Secondly, it would be nice in future to have a bit more formatted and localized code - piece of code above is hardly readable.
Thirdly - how are you actually testing to make sure that values are not set correctly?
Just FYI we have bigger example of complete app:
https://play.google.com/store/apps/details?id=com.mapbox.vision.teaser
source code:
https://github.com/mapbox/mapbox-vision-android-teaser

**Comment by estherooi** [comment]
@kiryldz alright! thanks a lot!
