### ISSUE TITLE
ERROR: You haven't set MAPBOX_ACCESS_TOKEN.

### ISSUE THREAD

**Issue by nole87** [mapbox/mapbox-vision-android#228]
Dear,

I get this error:
ERROR: You haven't set MAPBOX_ACCESS_TOKEN.
Please set it in <module>/src/main/res/values/developer-config.xml

And I set it in two developer-config.xml file, there is no more developer-config.xml file. Why I am getting this error.

Best,
Milan

**Comment by kiryldz** [comment]
Hi @nole87 - there are 3 modules with `developer-config.xml` files: app, recorder, replayer. Please set it in last remaining module and all should work fine.

**Comment by nole87** [comment]
I can't believe I didn't see it. I open all folders at least 5 times and also search all files in project and it always return 2 files in app and recorder. Maybe it was somehow generated when I close android studio and now open it again ...

**Comment by ggkangkang** [comment]
did it solve?
