### ISSUE TITLE
Could not get mapbox-android-vision-0.12.0.pom, Received status code 403 

### ISSUE THREAD

**Issue by icools** [mapbox/mapbox-vision-android#245]
Could not determine the dependencies of task ':Examples:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':Examples:debugCompileClasspath'.
   > Could not resolve com.mapbox.vision:mapbox-android-vision:0.12.0.
     Required by:
         project :Examples
      > Could not resolve com.mapbox.vision:mapbox-android-vision:0.12.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v1/vision/android/maven/com/mapbox/vision/mapbox-android-vision/0.12.0/mapbox-android-vision-0.12.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v1/vision/android/maven/com/mapbox/vision/mapbox-android-vision/0.12.0/mapbox-android-vision-0.12.0.pom'. Received status code 403 from server: Forbidden

**Comment by icools** [comment]
I download the aar directly from webstie(https://vision.mapbox.com/install/) , then it works.

**Comment by kiryldz** [comment]
Hello @icools .
Please take a closer look at https://account.mapbox.com/access-tokens/create/ mentioned in https://vision.mapbox.com/install/.
It seems that you created a token without `vision:download` scope.

**Comment by icools** [comment]
Yes,I forgot to select vision:download scope ,Thanks you .
