### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by CloudWangASP** [mapbox/mapbox-vision-android#247]
I try to run this project, and I've configured token information in [grade credentials, string.xml, and developer-config.xml ],but still failed to compile, so is there anything I need to pay attention to?

Here is the error info:

Could not determine artifacts for com.mapbox.navigator:mapbox-navigation-native:7.0.0
Could not get resource 'http://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.aar'.
Could not HEAD 'http://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.aar'. Received status code 401 from server: Unauthorized

**Comment by kiryldz** [comment]
Hi @CloudWangASP - I am able to download `aar` even by link you provided above.
Could you please tell us if could download it too?
Perhaps there was an issue with `bintray` when you tried, could you try again?

**Comment by CloudWangASP** [comment]
I already solved the compilation issues by downloading AAR manually,  however when I try to run this demo on my phone with external video source，there're no lane or traffic signs  recognized. 
What else do I need to do to see the normal render effect?（ps：I already changed the PATH_TO_VIDEO_FILE，and put my real lon&lat in）

**Comment by kiryldz** [comment]
Thanks for the information.
Please open another issue and state what exact example you are running and how you are testing it (e.g. just pointing on laptop screen or in real vehicle).

**Comment by Wesleywie** [comment]
> I already solved the compilation issues by downloading AAR manually, however when I try to run this demo on my phone with external video source，there're no lane or traffic signs recognized.
> What else do I need to do to see the normal render effect?（ps：I already changed the PATH_TO_VIDEO_FILE，and put my real lon&lat in）

Where did you insert the aar file ... I am having this issue aswell

**Comment by shahzaib-ch** [comment]
In my case issue was
`MAPBOX_DOWNLOADS_TOKEN="PASTE_YOUR_SECRET_TOKEN_HERE"` instead of `MAPBOX_DOWNLOADS_TOKEN=PASTE_YOUR_SECRET_TOKEN_HERE`.

Just removed quotes and it worked
