### ISSUE TITLE
Unable to resolve dependency for ':Examples@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.12.0.

### ISSUE THREAD

**Issue by anilemredurak** [mapbox/mapbox-vision-android#255]
Please Help Me,

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.aar'])
    implementation("com.serenegiant:common:$uvccamera_common") {
        exclude module: 'support-v4'
    }

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation "androidx.appcompat:appcompat:$android_x_appcompat"

    implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:$mapbox_sdk"
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation:$mapbox_navigation"
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation-ui:$mapbox_navigation"
    implementation "com.mapbox.mapboxsdk:mapbox-android-core:$mapbox_core"

    ktlint "com.pinterest:ktlint:$ktlint_version"

    implementation "com.mapbox.vision:mapbox-android-vision:$vision"
    implementation "com.mapbox.vision:mapbox-android-vision-ar:$vision"
    implementation "com.mapbox.vision:mapbox-android-vision-safety:$vision"
}

and eror code : Unable to resolve dependency for ':Examples@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.12.0.

![Ek Açıklama 2020-08-18 150834](https://user-images.githubusercontent.com/32162964/90511270-e26d1400-e164-11ea-89b0-b8cb8884183b.png)

**Comment by yunikkk** [comment]
Hey @RamenChan , have you added your Mapbox token as described at https://vision.mapbox.com/install/  in the Android section?

**Comment by anilemredurak** [comment]
The issue is resolved. @yunikkk thanks 🥇
