### ISSUE TITLE
OpenCL support for latest Google Pixel phones

### ISSUE THREAD

**Issue by pampas93** [mapbox/mapbox-vision-android#256]
Just a question. Vision sdk clearly states that OpenCL is a requirement and Google pixel phones do not support it. I wanted to know if this holds right for the latest pixel phones as well (4, 4a)

And if not, is there any alternative to work with the vision sdk on my pixel 4a?

**Comment by pampas93** [comment]
I tried running the examples on my Pixel 4a, and failed with a "Need Snapdragon-powered device with OpenCL support". But I'm running on Snapdragon 730G) and found `libOpenCL.so` and `libOpenCL-pixel.so` under both system/vendor/lib and system/vendor/lib64.

What else am I missing here?

**Comment by yunikkk** [comment]
Hey @pampas93 ! 
OpenCL is indeed a requirement. We haven't yet tried Pixel 4 and 4a, but if the binaries are present there is a chance it'll work. You could try to disable check at https://github.com/mapbox/mapbox-vision-android/blob/47a0d7988fec1b706356921564002b226cf3bfe6/Examples/src/main/java/com/mapbox/vision/examples/BaseActivity.java#L30 to test if it'll work on your phone

**Comment by pampas93** [comment]
> 
> 
> Hey @pampas93 !
> OpenCL is indeed a requirement. We haven't yet tried Pixel 4 and 4a, but if the binaries are present there is a chance it'll work. You could try to disable check at
> 
> https://github.com/mapbox/mapbox-vision-android/blob/47a0d7988fec1b706356921564002b226cf3bfe6/Examples/src/main/java/com/mapbox/vision/examples/BaseActivity.java#L30
> to test if it'll work on your phone

I was previously using release/0.11.0 branch; but now switched to dev. Looks like this check returns true (`SystemInfoUtils.INSTANCE.isVisionSupported()` returns true); so it doesn't get into the if. But, while running it on device, I get this error continuously.
`E/MACE: opencl_runtime.cc:278 No OpenCL platforms found`

Any idea what this is about?

**Comment by yunikkk** [comment]
> `E/MACE: opencl_runtime.cc:278 No OpenCL platforms found`
> 
> Any idea what this is about?

Yes, this means that OpenCL is indeed not working on your Pixel, even with binary libraries available. Can be permissions issue, if opencl is not listed as publicly available, that is often the case for embedded Android. 

Unfortunately nothing we can do in the moment, but we plan to add Pixel-s support in future. The only option you have right now is to use different device.

**Comment by pampas93** [comment]
@yunikkk Thanks for looking into it.

**Comment by pampas93** [comment]
@yunikkk Any updates on supporting Google pixels yet? Or can you send me a list of android phones that do work/support the vision API?

**Comment by yunikkk** [comment]
> @yunikkk Any updates on supporting Google pixels yet? Or can you send me a list of android phones that do work/support the vision API?

unfortunately no updates regarding Pixels yet. Most of modern devices are supported though, Pixels are the rare exception. Pretty outdated list is at https://docs.mapbox.com/android/vision/guides/#requirements, but you should expect most newer devices to be supported as well.
