### ISSUE TITLE
Support for Mediatek MT6757 Helio P20 (16 nm) Chipset with Mali-T880MP2 GPU. 

### ISSUE THREAD

**Issue by sartaaj13** [mapbox/mapbox-vision-android#258]
I am trying to run MapBox Vision on My Samsung J7 Max. I chceked the **libOpenCL.so** file is present in /system/vendor/lib folder, still I am getting this issue

> I/MACE: mace.cc:957 Create MaceEngine from model graph proto and weights data
I/MACE: mace.cc:500 Creating MaceEngine, MACE version: v0.11.0-rc0-241-gc0c4f29
E/MACE: opencl_runtime.cc:278 No OpenCL platforms found
I/MACE: mace.cc:682 Destroying MaceEngine
I/MACE: mace.cc:539 Initializing MaceEngine
W/MACE: mace.cc:58 The device does not support OpenCL
I/MACE: mace.cc:543 CheckGPUAvalibility(net_def, device_.get()) failed with error: Out of resources

libOpenCL.so file in Device

![image](https://user-images.githubusercontent.com/43455430/96575547-83578700-12ee-11eb-84ba-766fdba981a4.png)

I think it is because the Chipset is not supported.
Anything I am missing!!!!

**Comment by sartaaj13** [comment]
I checked the device info using the **SystemInfoUtils** and got the response
![image](https://user-images.githubusercontent.com/43455430/96577135-d6323e00-12f0-11eb-8e23-045bdb0b481d.png)

**Comment by yunikkk** [comment]
Hi @sartaaj13 , unfortunately it seems the device won't be supported by Vision. 
Most probably device does not have permissions on the system level to the openCl binaries. So they are present but we are not able to use them. 
The only thing you could try is different device.
