### ISSUE TITLE
Navigate user via outside custom service  array of directions coordinates

### ISSUE THREAD

**Issue by rgouzal** [mapbox/mapbox-vision-android#268]
I am using in my app my own custom directions api service which gets directions or route of source and destination coordinates. Is there a possible way to navigate depending on custom route coordinates?

**Comment by yunikkk** [comment]
Hi! 
Do you try to test it on the road with your custom route information provider? If so - you can map the route to the array of RoutePoints and feed it ti Vision, as shown in https://docs.mapbox.com/android/vision/guides/ar/#route-line.

**Comment by rgouzal** [comment]
@yunikkk I am getting route coordinates via a different API (openrouteservice.org) so are you saying I have to loop through each coordinate and map it to a routepoints I see that RoutePoint class is final and does not have a setter or getter same with Route class?

**Comment by yunikkk** [comment]
> @yunikkk I am getting route coordinates via a different API (openrouteservice.org) so are you saying I have to loop through each coordinate and map it to a routepoints I see that RoutePoint class is final and does not have a setter or getter same with Route class?

Exactly, you need to map coordinates you retrieve from that API to RoutePoints, similarly to https://docs.mapbox.com/android/vision/examples/basic-ar-navigation/. 
It's final since it's in fact kotlin data class and you should be able to create and init it with constructor.

**Comment by rgouzal** [comment]
@yunikkk okay but how can I map it since Route class and RoutePoint class does not have a public setters?

**Comment by rgouzal** [comment]
@yunikkk and what about a profile of "walking" does AR navigation work only for profile "driving" by lane detection?
