### ISSUE TITLE
Not able to navigate or get the route line on AR navigation

### ISSUE THREAD

**Issue by rgouzal** [mapbox/mapbox-vision-android#269]
I have tried the Teaser version after downloading it from playstore and playing with it just to get an idea of how AR navigation should work and should be. I tried to use some code on this project with my own React Native project to bind AR navigation to a react native custom module but I don't seem to get AR navigation route line which should be shown on screen.

Note:  I am getting routes by mapbox navigation sdk and not  with some outside service.

**Comment by yunikkk** [comment]
Hey @rgouzal , to be able to help we'll need more info about the project you build. Please share the code you use to integrate Vision and describe the setup in more details

**Comment by rgouzal** [comment]
@yunikkk Never mind I will close the issue I was able to get it working, just question is it okay if I use it to publish a react-native package that gets from user routepoints without using mapbox remote navigation kind of for local offline navigation?

**Comment by yunikkk** [comment]
@rgouzal should be ok, just curios how do you calculate offline routes?

**Comment by rgouzal** [comment]
@yunikkk Actually its not offline, but route is fetched before from https://openrouteservice.org and stored on local database so user can access the route offline even if they don't have internet coverage. So once route navigation on arrival and done it will remove the route from database.
