### ISSUE TITLE
Mapbox vision SDK sample is not working

### ISSUE THREAD

**Issue by akhilmukund** [mapbox/mapbox-vision-android#270]
I try to set up the Mapbox vision sample app (https://github.com/mapbox/mapbox-vision-android), but not able to test the Mapbox Vision SDK sample app.
Dependency files are not downloading due to the Forbidden error.

Error :
Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project.

Could you please share the details for how to fix this issue?

Followed the instructions mentioned on https://docs.mapbox.com/android/vision/guides/install/ page and used new tokens but the same issue still exists.

Gradle file: 
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://mapbox.bintray.com/mapbox" }
        maven {
            url 'https://api.mapbox.com/downloads/v1/vision/android/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username "mapbox"
                password 'MAP_BOX_KEY'
            }
        }
        maven { url 'http://raw.github.com/saki4510t/libcommon/master/repository/' }
    }

}
```

Gradle dependency :
```
    implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:$mapbox_sdk"
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation:$mapbox_navigation"
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation-ui:$mapbox_navigation"
    implementation "com.mapbox.mapboxsdk:mapbox-android-core:$mapbox_core"
    implementation "com.mapbox.vision:mapbox-android-vision:0.13.0"
    implementation "com.mapbox.vision:mapbox-android-vision-ar:0.13.0"
    implementation "com.mapbox.vision:mapbox-android-vision-safety:0.13.0"

    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:5.8.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.8.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-core:5.8.0'

    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.8.0'
```

**Comment by yunikkk** [comment]
Hi @akhilmukund ! 
This repo sample has not been updated, indeed. We've changed maven endpoints configuration, please check 'https://docs.mapbox.com/android/vision/guides/install/#add-the-dependency'  carefully again. The new gradle dependency configuration is different, correct url is `url 'https://api.mapbox.com/downloads/v2/releases/maven'` instead of `url 'https://api.mapbox.com/downloads/v1/vision/android/maven'`

**Comment by yunikkk** [comment]
Related https://github.com/mapbox/mapbox-navigation-android/issues/4533

@akhilmukund it seems at the moment you won't be able to retrieve navigation-native 7.0.0 even from the updated maven. Will need to wait while nav-native will revive old versions from the Bintray mirror.

**Comment by yunikkk** [comment]
UPD : navigation SDK seem to have reuploaded all the artifacts to the SDK registry, we'll update build.gradle to get the dependencies from the correct maven repo
