### ISSUE TITLE
MapBox Vision not working Forbidden Status: 403

### ISSUE THREAD

**Issue by sohail-niazi** [mapbox/mapbox-vision-android#272]
Hi, I am getting forbidden error on my Android project for last 2 days. I have installed a new android studio on new laptop, since then I am not able to build my project. Following is the error I am facing: 
`

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.mapbox.vision:mapbox-android-vision:0.13.0.
     Required by:
         project :app
      > Could not resolve com.mapbox.vision:mapbox-android-vision:0.13.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.mapbox.vision:mapbox-android-vision:0.13.0.
         > Could not get resource 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'.
            > Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision/0.13.0/mapbox-android-vision-0.13.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.13.0.
     Required by:
         project :app
      > Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.13.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.13.0.
         > Could not get resource 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'.
            > Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/vision/mapbox-android-vision-ar/0.13.0/mapbox-android-vision-ar-0.13.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.navigator:mapbox-navigation-native:7.0.0.
     Required by:
         project :app > com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:7.0.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.mapbox.navigator:mapbox-navigation-native:7.0.0.
         > Could not get resource 'https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom'.
            > Could not GET 'https://mapbox.bintray.com/mapbox/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom'. Received status code 403 from server: Forbidden
`

I am using following dependencies and were working fine on my last project. There is no change in MAPBOX_TOKEN for any dependency.
```
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-building-v9:0.7.0'
    implementation "com.mapbox.vision:mapbox-android-vision:0.13.0"
    implementation "com.mapbox.vision:mapbox-android-vision-ar:0.13.0"
    implementation "com.mapbox.mapboxsdk:mapbox-android-core:1.3.0"
    implementation "com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0"
```

**Comment by yunikkk** [comment]
@sohail-niazi please check the build.gradle file with maven configuration, e.g. https://github.com/mapbox/mapbox-vision-android/blob/dev/build.gradle#L21. 
Section with setup instructions is at https://docs.mapbox.com/android/vision/guides/install/#configure-credentials

**Comment by sohail-niazi** [comment]
My Gradle is using v1 link and there is no plan to switch to v2 anytime soon. But there is no change in my gradle code for over a year

```
maven {
            url 'https://api.mapbox.com/downloads/v1/vision/android/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username project.properties['mapboxMavenUser'] ?: ""
                password project.properties['mapboxMavenToken'] ?: ""
            }
        }
```

**Comment by yunikkk** [comment]
> My Gradle is using v1 link and there is no plan to switch to v2 anytime soon. But there is no change in my gradle code for over a year
> 
> ```
> maven {
>             url 'https://api.mapbox.com/downloads/v1/vision/android/maven'
>             authentication {
>                 basic(BasicAuthentication)
>             }
>             credentials {
>                 username project.properties['mapboxMavenUser'] ?: ""
>                 password project.properties['mapboxMavenToken'] ?: ""
>             }
>         }
> ```

Unfortunately, v1 is no longer supported / working, you have to update the to v2 to make the project build again. Also you'll need the new token with the updated scope, check the docs please https://docs.mapbox.com/android/vision/guides/install/#configure-credentials

**Comment by sohail-niazi** [comment]
Thanks, it worked after v2 switch and new token 👍
