### ISSUE TITLE
Example Demos: Android 9.0 Devices require Foreground Service Permission

### ISSUE THREAD

**Issue by BULVRDapp** [mapbox/mapbox-vision-android#90]
Running the latest examples with version 0.3.0, Android 9.0+ devices will crash as they require Foreground Service permission when attempting to run the navigation example. Crash happens after selecting a destination. 

Just need to add in the repo:
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

**Comment by RingerJK** [comment]
I'll assign permission for Foreground Services
